fix - disable TF Plan Status

diff --git a/.github/workflows/dev_deploy.yml b/.github/workflows/dev_deploy.yml
--- a/.github/workflows/dev_deploy.yml
+++ b/.github/workflows/dev_deploy.yml
@@ -43,9 +43,9 @@ jobs:
         run: terraform plan -no-color
         continue-on-error: true
 
-      - name: Terraform Plan Status
-        if: steps.plan.outcome == 'failure'
-        run: exit 1
+      # - name: Terraform Plan Status
+      #   if: steps.plan.outcome == 'failure'
+      #   run: exit 1
 
       # - name: Terraform Apply
       #   run: terraform apply -auto-approve
